### ISSUE TITLE
Cache MeasurementSet Constants

### ISSUE THREAD

**Issue by calgray** [ICRAR/leap-accelerate#56]
Constants can be precalculated per MeasurementSet for members such as A, Ad, A1, A1d matrices that may ideally be loaded from a file cache.

The best key to cache these files with should be a combination of:
* MeasurementSet name
* MeasurementSet last modified time
* stations override
* autocorrelations flag
* version number

**Comment by mdolensk** [comment]
While caching results by MS may be useful in certain scenarios including debugging/testing, it should be noted that in the case of SKA operations we don't expect computational resources to be available for multiple runs on the same data and consequently one would have to make the case for provisioning a dedicated storage space for caching. Items like the autocorrelation flag should be passed down through the telescope configuration (e.g. scheduling block metadata).

**Comment by calgray** [comment]
As of 0.7.0-beta there is now opt-out caching support for matrix Ad
